### PR TITLE
upper threshold, (cosine) angular distance, limit scaling

### LINKED ISSUE #1: distance metric, word vectors and references
afaict, you are using euclidean distances, however these are not expected to work well for high dimensional problems. namely for word vectors, one should use cosine distance. these is equivalent to euclidean distance for normalized vectors, however afaict you are not using the normalized vectors, but the raw fasttext vectors which are not normalized. i would suggest: (1) use normalized vectors for word vectors example. (2) allow using a custom metric. (3) is there any writeup explaing star-clustering method? (4) do you have references to other methods doing similar clustering on word vectors? would be interesting to see some comparison for this specific use case which you are highlighting (and is very interesting). thanks!

### PR DESCRIPTION
**Pull request by shy1**
adding multiple arguments to the fit() method probably goes against the intended parameter-free spirit of the project, but everything should work the same as the original code if default values are used and some of the new word cluster results are fairly impressive

### CODE REVIEW

**Review by josephius — APPROVED** [review]
This looks good.  I really appreciate how quickly you managed to whip this up, and over a weekend too!

**Comment by shy1** [comment]
> This looks good. I really appreciate how quickly you managed to whip this up, and over a weekend too!

thanks, i recently quit my software engineering job to focus on my research and do part-time freelance work, but i haven't actually started seeking out freelance work yet and my current research requires very little activity outside of waiting for models to finish training on large datasets, so i've got a lot of excess productivity to spare.

plus i've had a few language modeling ideas involving word embedding clusters in the past, but a lack of clustering experience was a pretty big mental roadblock preventing me from attempting to implement them. your ready-to-go word vector test script could not have been more perfect for clearing that roadblock. and seeing how different distance formulations affected the types of cluster groupings has even inspired some new ideas, so this has been a very worthwhile use of my time.

**Comment by shy1** [comment]
you see any reason not to delete the feature branch now that it's been merged? doesn't make much difference at this stage, but definitely a good practice to keep things from getting cluttered over time. 

the hoarder in me hates it, but i've seen enough barely navigable nightmares working with large teams to know that it's the right thing to do.

**Comment by josephius** [comment]
Good to hear my test script was of use to help you with your mental block.

Okay, branch deleted!

**Pull request merged**
